// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA94SmzKs143TA_TjCmJsDA9pBZmT3wcIA',
    appId: '1:948835868913:web:1b7d4d0da1d45f9328c950',
    messagingSenderId: '948835868913',
    projectId: 'verbaldetox-8d690',
    authDomain: 'verbaldetox-8d690.firebaseapp.com',
    storageBucket: 'verbaldetox-8d690.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdVgJqei58ToZr0Ex0LDpjzP1iPWdmPvU',
    appId: '1:948835868913:android:7d140dbdafe0e23a28c950',
    messagingSenderId: '948835868913',
    projectId: 'verbaldetox-8d690',
    storageBucket: 'verbaldetox-8d690.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs-DpbccLk2MlxEgemcDVqRGDMGNu7s_E',
    appId: '1:948835868913:ios:89e51afe5c86f0af28c950',
    messagingSenderId: '948835868913',
    projectId: 'verbaldetox-8d690',
    storageBucket: 'verbaldetox-8d690.firebasestorage.app',
    iosBundleId: 'com.example.verbaldetox',
  );
}
