// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFXHRwv7qm6vkFZR04TfSXH6qveuQFJck',
    appId: '1:160302376986:web:c6a328c0c2df92705489a3',
    messagingSenderId: '160302376986',
    projectId: 'zenn-hackthon-2',
    authDomain: 'zenn-hackthon-2.firebaseapp.com',
    storageBucket: 'zenn-hackthon-2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKai3wxfqG9epJiqSK1UBYMMoF3ntvpD8',
    appId: '1:160302376986:android:9f967a275901f65f5489a3',
    messagingSenderId: '160302376986',
    projectId: 'zenn-hackthon-2',
    storageBucket: 'zenn-hackthon-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtQ9sGNHtdmbx8jh17gWBdrXV5fXSBOR8',
    appId: '1:160302376986:ios:8a80424733b7b2345489a3',
    messagingSenderId: '160302376986',
    projectId: 'zenn-hackthon-2',
    storageBucket: 'zenn-hackthon-2.firebasestorage.app',
    iosBundleId: 'com.example.verbaldetox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtQ9sGNHtdmbx8jh17gWBdrXV5fXSBOR8',
    appId: '1:160302376986:ios:8a80424733b7b2345489a3',
    messagingSenderId: '160302376986',
    projectId: 'zenn-hackthon-2',
    storageBucket: 'zenn-hackthon-2.firebasestorage.app',
    iosBundleId: 'com.example.verbaldetox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFXHRwv7qm6vkFZR04TfSXH6qveuQFJck',
    appId: '1:160302376986:web:55393fcec0639cc45489a3',
    messagingSenderId: '160302376986',
    projectId: 'zenn-hackthon-2',
    authDomain: 'zenn-hackthon-2.firebaseapp.com',
    storageBucket: 'zenn-hackthon-2.firebasestorage.app',
  );

}